### ISSUE TITLE
Show warning to setup aws keys first

### ISSUE THREAD

**Issue by msoni11** [taketwotech/moodle-quizaccess_quizproctoring#22]
Our plugin is purely dependent on AWS rekognition proctoring. If the correct settings are not in place, it will throw error during the quiz. We need to block that at initial level only if AWS params are not set under settings.

**Comment by jainkavita31** [comment]
@msoni11 i commit the changes.. please let me know if need any changes.

**Comment by msoni11** [comment]
We can't expose keys openly in browser. We need to think about another solution. I think https://github.com/taketwotech/moodle-quizaccess_quizproctoring/blob/master/rule.php#L240 is right place for that check.

**Comment by jainkavita31** [comment]
@msoni11 apply solution on prevent_access function. we need to show warning messages to admin and student.. please have a look..

**Comment by jainkavita31** [comment]
@msoni11 done . Add link for AWS configuration

**Comment by msoni11** [comment]
Thanks.
