### ISSUE TITLE
Orderline Related Settings to be removed

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#27]
We need to do following things:
1. 'Orderline Related Settings' section to be removed.
2. Under 'Orderline Related Settings' the 'Quiz Proctoring video link' textbox should be transferred to 'Extra Restriction on attempts Section'  and all other three textboxes should be removed.
 
**We need to remove/ delete these using Upgrade Delete.**

![hsfjhskdajfhk](https://user-images.githubusercontent.com/112858824/225524970-4c49c92a-c46a-491a-8319-39216d4d845f.png)

**Comment by jainkavita31** [comment]
@msoni11 : Remove orderline settings.. shift  'Quiz Proctoring video link' into  'Extra Restriction on attempts Section'
