### ISSUE TITLE
'Proctoring Images' Button

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#43]
1. System should display 'Proctoring Images' Button in quiz review.
2. System should have various user role permissions for 'Proctoring Images' Button.
3. System should have 'Proctoring images show' checkbox in plugins -> Activity modules -> quiz -> proctoring quiz access rule

**Comment by nidhsharma11** [comment]
testing done! 
Working correctly.

**Comment by msoni11** [comment]
Thanks
