### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#44]
System should ensure backward compatibility for all the new changes that are applied.

**Comment by jainkavita31** [comment]
@nidhsharma11 i checked  backward compatibility our plugin is working fine.
My approach is i install fresh moodle and upload our plugin from this link
https://moodle.org/plugins/quizaccess_quizproctoring/versions

after that i attempt some quiz.. than from development branch i copy the code with our plugin.. than i attempt new quiz with user than images and identity is properly working.. upload image is now not as required field.

**Comment by msoni11** [comment]
What about previous images? Were you able to review images from previous
attempts that you did before upgrading plugin?

**Comment by jainkavita31** [comment]
yes able to see previous images also

**Comment by msoni11** [comment]
Great, thanks!

**Comment by nidhsharma11** [comment]
I have ensured from the developers.
I have also tested this on dev.
Working correctly.

**Comment by msoni11** [comment]
Thanks
