### ISSUE TITLE
warning help button text to change

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#45]
![image](https://user-images.githubusercontent.com/112858824/230076335-5074216f-a56c-465d-9ceb-b9530a22c329.png)

Number of warnings a user should receive before the user gets disqualified from the proctored exam.

**Comment by jainkavita31** [comment]
Update warning button text is updated in en and fr lang. please deploy the changes

**Comment by nidhsharma11** [comment]
Testing done. Working correctly!

**Comment by msoni11** [comment]
Thanks
