### ISSUE TITLE
'Upload image' to be removed from a required field

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#46]

**Comment by nidhsharma11** [comment]
![image](https://user-images.githubusercontent.com/112858824/230271898-091dba8a-47b2-4b07-942e-af8fc19fac3f.png)

**Comment by jainkavita31** [comment]
Remove 'upload image' as required field.

**Comment by nidhsharma11** [comment]
testing done! 
Working correctly.
