### ISSUE TITLE
Time interval should not be visible if proctoring is not enabled

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#47]
just like warning number is not visible if proctoring enable is 'No'. Time interval should also be hidden.
![image](https://user-images.githubusercontent.com/112858824/230080044-143503a7-7acd-4c00-adac-7e88612255ae.png)
![image](https://user-images.githubusercontent.com/112858824/230080411-566538cb-b53e-43de-8cfb-c74c4cb0fdc2.png)

**Comment by jainkavita31** [comment]
Hide time interval when proctoring is not enabled. Please deploy the changes

**Comment by nidhsharma11** [comment]
Testing Done. Working correctly!

**Comment by msoni11** [comment]
Thanks
