### ISSUE TITLE
incorrect use of DML functions

### ISSUE THREAD

**Issue by danmarsden** [taketwotech/moodle-quizaccess_quizproctoring#5]
Please use placeholders - do not inject variables into in-line sql queries - for example:

https://github.com/taketwotech/quizproctoring/blob/master/lib.php#L121

more info:
https://moodledev.io/docs/apis/core/dml#placeholders

Please check all your sql and make sure they use placeholders.

**Comment by ashiyadav1** [comment]
@msoni11 : Done !!

**Comment by msoni11** [comment]
Thanks. Closing it.
