### ISSUE TITLE
Previous button is not working

### ISSUE THREAD

**Issue by jainkavita31** [taketwotech/moodle-quizaccess_quizproctoring#51]

**Comment by jainkavita31** [comment]
please deploy the changes.

**Comment by ashiyadav1** [comment]
@nidhsharma11 : done

**Comment by nidhsharma11** [comment]
@jainkavita31 :When there is only 1 image then Should it have the previous and next button?
Have we applied a solution for this as well?

**Comment by jainkavita31** [comment]
@nidhsharma11 done with issue #60

**Comment by nidhsharma11** [comment]
testing done! 
Working correctly.

**Comment by msoni11** [comment]
Thanks
