### ISSUE TITLE
user role permission text to change

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#53]
Change the text of this user role permission.

![image](https://user-images.githubusercontent.com/112858824/230383028-794040c2-151a-433a-a629-d2623f4e1a53.png)

**Comment by jainkavita31** [comment]
Text updated. please deploy the changes

**Comment by ashiyadav1** [comment]
@nidhsharma11 : done

**Comment by nidhsharma11** [comment]
Testing done. It's working correctly.

**Comment by ashiyadav1** [comment]
@nidhsharma11 : Done

**Comment by msoni11** [comment]
Thanks
