### ISSUE TITLE
Proctoring identity button should not show in multiple attempts

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#62]
When I attempt the quiz for the 1st time, both the 'Procting Identity' and 'Proctoring images' button works fine.
in 2nd and multiple attempts from the same user: 'Procting Identity' Button should not show.

**Comment by nidhsharma11** [comment]
Beacuse we do not ask for 'Procting Identity' after 1st attempt. so this button should also not be visible.

**Comment by nidhsharma11** [comment]
![image](https://user-images.githubusercontent.com/112858824/230831941-e91b3e2a-0124-4257-b6c4-e39c951a89ec.png)


userid: test10

**Comment by nidhsharma11** [comment]
@jainkavita31 : The 'Proctoring Identity' Button is gone for 1st attempt also. Please check.
It should be present only in 1st attempt.
![image](https://user-images.githubusercontent.com/112858824/230874713-8cc5c27d-f976-4ddf-a4c2-f9170c6025da.png)

**Comment by nidhsharma11** [comment]
testing done! 
Working correctly.

**Comment by msoni11** [comment]
Thanks
