### ISSUE TITLE
Popup in case of no warnings.

### ISSUE THREAD

**Issue by nidhsharma11** [taketwotech/moodle-quizaccess_quizproctoring#63]
case1: 
1st attempt + No warning detected = Only main image is shown in 'Proctoring Images' Button
**Case 1 is working correctly**

Case2:
2nd attempt + No warning detected = On click of 'Proctoring Images' Button it should show a pop up that 'No warnings were detected'

Please work on case2.
In case of multiple attempts when no warnings are detected there should be a popup.

**Comment by nidhsharma11** [comment]
![image](https://user-images.githubusercontent.com/112858824/230832165-74a8da11-90f6-423a-b624-15c391ba0c82.png)

userid: test10

no warnings are there in 3rd attempt.

**Comment by jainkavita31** [comment]
please deploy the changes.
 during multiple attempts 'no warnings detected'  popup is shown.
fix issues #62 with this

**Comment by nidhsharma11** [comment]
testing done! 
Working correctly.

**Comment by msoni11** [comment]
Thanks
