### ISSUE TITLE
require_login should only be included once

### ISSUE THREAD

**Issue by danmarsden** [taketwotech/moodle-quizaccess_quizproctoring#8]
https://github.com/taketwotech/quizproctoring/blob/master/ajax.php#L27

you have it multiple times on this page, you should also pass $cm into the require_login call if this page requires it as will also implement further security checks. (can this user view this activity)

**Comment by ashiyadav1** [comment]
@msoni11 : Done with changes 4.1 !!

**Comment by msoni11** [comment]
Thanks. Closing it.
