### ISSUE TITLE
Without choosing Extra restrictions on attempts error showing during quiz creation

### ISSUE THREAD

**Issue by jainkavita31** [taketwotech/moodle-quizaccess_quizproctoring#83]
![Error](https://user-images.githubusercontent.com/98306598/232752364-5c88b6a2-f68a-4732-a667-09f3afc8cec5.png)

**Comment by jainkavita31** [comment]
@msoni bug is there..it fixed now.. tested by nidhi.. please deploy on server.

**Comment by msoni11** [comment]
Thanks
