### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by jainkavita31** [taketwotech/moodle-quizaccess_quizproctoring#85]
Stack trace:
line 397 of /mod/quiz/accessrule/quizproctoring/rule.php: TypeError thrown
line 432 of /mod/quiz/accessmanager.php: call to quizaccess_quizproctoring->setup_attempt_page()
line 63 of /mod/quiz/review.php: call to quiz_access_manager->setup_attempt_page()

**Comment by jainkavita31** [comment]
Fix error.
@nidhsharma11 please test after deployment.

**Comment by nidhsharma11** [comment]
@msoni11 : I have done the testing.
error did not come.
It works fine.
you can deploy.

**Comment by msoni11** [comment]
Thanks
