### ISSUE TITLE
No action  then i press button "Proctoring Images"

### ISSUE THREAD

**Issue by Akshuradus** [taketwotech/moodle-quizaccess_quizproctoring#88]
When I try to review a quiz attempt, I click on the "proctoring image"  button. No action occurs.
In  log file of  web server  i see  request 
for example

 /moodle/mod/quiz/accessrule/quizproctoring/ajax_report.php?attemptid=14&userid=3&quizid=1 HTTP/1.1" 200 179181 "https://192.168.1.110/moodle/mod/quiz/review.php?attempt=14&cmid=2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"

I try  to  open  as  URL  and  see  next one JSON data

![image](https://github.com/taketwotech/moodle-quizaccess_quizproctoring/assets/7982662/35f10c43-71ff-40ea-83a6-17ef214dd8a1)

![image](https://github.com/taketwotech/moodle-quizaccess_quizproctoring/assets/7982662/20366cdc-f4e5-42de-9e26-7ad8d8163665)

and headers 

Connection | Keep-Alive
Content-Type | application/json; charset=utf-8
Date | Thu, 01 Feb 2024 18:32:47 GMT
Expires | Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive | timeout=5, max=100
Pragma | no-cache
Server | Apache/2.4.57 (Ubuntu)
Transfer-Encoding | chunked
X-Content-Type-Options | nosniff
X-Frame-Options | DENY

I try  differet  browsers firefox, edge, chrome - same  result.

**Comment by msoni11** [comment]
@Akshuradus You will need to wait for complete page refresh first before clicking on button.

**Comment by msoni11** [comment]
We've release another version with improved custom popup generator. It is backward compatible as well. It should work with older as well as new version.
