### ISSUE TITLE
incorrect location for settings

### ISSUE THREAD

**Issue by danmarsden** [taketwotech/moodle-quizaccess_quizproctoring#9]
Please do not add plugin specific settings to the global $CFG variable, but use the config_plugins table - setting names like "$CFG->quizaccess_quizproctoring_aws_key;" are incorrect.
in your settings.php file the settings should look more like:
```
admin_setting_configtext('quizaccess_quizproctoring\aws_key')
```
note the slash after the plugin name..

Plugins can then use the functions: get_config($plugin, $name). (or set_config($name, $value, $plugin) if you aren't using settings.php)

more information on admin settings is here: https://moodledev.io/docs/apis/subsystems/admin

Note this is usually a blocker for plugins db approval.

**Comment by ashiyadav1** [comment]
@msoni11 : Done !!

**Comment by msoni11** [comment]
Thanks. Closing it.
